# Generated by Django 4.2.14 on 2024-07-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_completedtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedTask',
        ),
    ]
